[package]
name = "lazed"
version = "0.0.1"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "lazed_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
tauri-plugin-notification = "2.4.0"
tauri-plugin-dialog = "2.7.3"
notify-rust = "4.18"
keyring = { version = "3", default-features = false, features = ["apple-native"] }
