#!/usr/bin/env python3
"""Failure injection against disposable daemons and a fake herdr. No live socket."""
import json
import os
from pathlib import Path
import socket
import subprocess
import tempfile
import threading
import time
import unittest

ROOT = Path(__file__).resolve().parents[1]


class ReliabilityTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix="lazed-reliability-", dir="/private/tmp")
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.repo = self.root / "main repo"
        self.repo.mkdir()
        self.git("init", "-q")
        self.git("-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid",
                 "-c", "commit.gpgsign=false", "commit", "--allow-empty", "-qm", "fixture")
        self.linked = self.root / "linked checkout"
        self.git("worktree", "add", "-qb", "fixture", str(self.linked))
        self.counts = {}
        self.drop_next = set()
        self.lock = threading.Lock()
        self.quit = threading.Event()
        self.listener = socket.socket(socket.AF_UNIX)
        self.socket = self.root / "herdr.sock"
        self.listener.bind(str(self.socket))
        self.listener.listen()
        self.listener.settimeout(0.1)
        self.thread = threading.Thread(target=self.serve, daemon=True)
        self.thread.start()
        self.addCleanup(self.stop_fixture)
        fake = self.root / "herdr"
        # The fixture path is generated by tempfile, never user shell input.
        fake.write_text("#!/bin/sh\nprintf '%s\\n' '" + json.dumps({"server": {"socket": str(self.socket)}}) + "'\n")
        fake.chmod(0o700)
        env = dict(os.environ, LAZED_STATE_DIR=str(self.root / "state"),
                   LAZED_CONFIG_DIR=str(self.root / "config"), HERDR_BIN=str(fake),
                   LAZED_HERDR_SESSION="fixture")
        self.log = (self.root / "daemon.log").open("w")
        self.addCleanup(self.log.close)
        self.daemon = subprocess.Popen([str(ROOT / "daemon/target/debug/lazed"), "server", "--foreground"],
                                       env=env, stdout=subprocess.DEVNULL, stderr=self.log)
        self.addCleanup(self.stop_daemon)
        for _ in range(100):
            if self.daemon.poll() is not None:
                self.fail((self.root / "daemon.log").read_text())
            try:
                self.rpc("session.status")
                break
            except OSError:
                time.sleep(0.03)
        else:
            self.fail("fixture daemon did not start")

    def git(self, *args):
        return subprocess.check_output(["git", "-C", str(self.repo), *args], stderr=subprocess.DEVNULL, text=True).strip()

    def stop_daemon(self):
        if self.daemon.poll() is None:
            self.daemon.terminate()
            self.daemon.wait(timeout=5)

    def stop_fixture(self):
        self.quit.set()
        self.listener.close()
        self.thread.join(timeout=2)

    def serve(self):
        while not self.quit.is_set():
            try:
                conn, _ = self.listener.accept()
            except socket.timeout:
                continue
            except OSError:
                break
            with conn:
                try:
                    conn.settimeout(2)
                    with conn.makefile("r") as reader:
                        req = json.loads(reader.readline())
                    method = req["method"]
                    with self.lock:
                        self.counts[method] = self.counts.get(method, 0) + 1
                        if method in self.drop_next:
                            self.drop_next.remove(method)
                            continue  # accepted the request, then lost the reply
                    result = {}
                    error = None
                    if method == "session.snapshot":
                        result = {"snapshot": {"workspaces": [], "panes": [], "tabs": [], "agents": []}}
                    elif method == "events.subscribe":
                        error = {"code": "fixture", "message": "stream disabled"}
                    elif method in ("workspace.create", "worktree.create"):
                        result = {"workspace": {"workspace_id": "w1"}, "tab": {"tab_id": "w1:t1"},
                                  "root_pane": {"pane_id": "w1:p1"}, "worktree": {"checkout_path": str(self.linked)}}
                    elif method in ("agent.start", "agent.get"):
                        result = {"pane_id": "w1:p1", "agent_status": "idle", "launch_pending": False}
                    elif method == "agent.prompt":
                        error = {"code": "agent_not_ready", "message": "refused without writing input"}
                    reply = {"id": req["id"], "error": error} if error else {"id": req["id"], "result": result}
                    conn.sendall((json.dumps(reply) + "\n").encode())
                except (OSError, ValueError):
                    pass

    def rpc(self, method, params=None):
        with socket.socket(socket.AF_UNIX) as conn:
            conn.settimeout(5)
            conn.connect(str(self.root / "state/lazed.sock"))
            conn.sendall((json.dumps({"id": 1, "method": method, "params": params or {}}) + "\n").encode())
            with conn.makefile("r") as reader:
                return json.loads(reader.readline())

    def test_mutations_are_not_replayed_after_losing_the_reply(self):
        for method in ("workspace.create", "agent.prompt"):
            with self.lock:
                self.drop_next.add(method)
                before = self.counts.get(method, 0)
            response = self.rpc("herdr.call", {"method": method, "params": {"text": "once"}})
            self.assertIn("herdr_submission_uncertain", response["error"])
            self.assertEqual(self.counts[method] - before, 1)

    def test_linked_import_opens_the_real_main_checkout(self):
        result = self.rpc("project.create", {"cwd": str(self.linked), "init_skills": False})["result"]
        self.assertEqual(result["project"]["repo_root"], str(self.repo))
        self.assertEqual(result["workspace"]["path"], str(self.repo))
        self.assertTrue(result["workspace"]["is_main"])

    def test_rejected_initial_prompt_stays_uncertain_and_refuses_followup(self):
        params = {"request_id": "rejected", "cwd": str(self.repo), "kind": "codex", "text": "initial", "branch": "task"}
        result = self.rpc("task.start", params)["result"]
        self.assertEqual(result["phase"], "submission_uncertain")
        self.assertIsNone(result["receipt"])
        self.assertEqual(self.rpc("task.status", {"task_id": "rejected"})["result"]["phase"], "submission_uncertain")
        self.assertEqual(self.rpc("task.start", params)["result"]["phase"], "submission_uncertain")
        response = self.rpc("task.tell", {"task_id": "rejected", "request_id": "followup", "text": "next"})
        self.assertIn("task_not_settled", response["error"])
        self.assertEqual(self.counts["agent.prompt"], 1)
        self.assertEqual(self.counts["agent.start"], 1)


if __name__ == "__main__":
    unittest.main()
